# Generated by Django 5.1.3 on 2024-11-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='message',
            new_name='msg',
        ),
    ]
